### ISSUE TITLE
Not storing API KEy

### ISSUE THREAD

**Issue by thesach** [GeekyEggo/GoveeController#3] opened 2022-01-26 20:14 UTC
## Description

I have the API key entered and it works but then when I go to push the button some time later the key is not showing the button.  

## Reproduction Steps

_Steps to reproduce the behaviour:_
2. Click on '...'
3. Scroll down to '...'
4. See error.

## Expected Behaviour

_A clear and concise description of what you expected to happen._

## Logs and Screenshots

- _Please attach logs found at `%appdata%\Elgato\StreamDeck\Plugins\com.geekyeggo.goveecontroller.sdPlugin\logs`_
- _If applicable, add screenshots to help explain the problem._

**Comment by GeekyEggo** [comment] 2022-01-26 20:40
Hey @thesach, could I ask you to download the latest beta version from [here](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin) and try using the plug-in again. When you encounter the problem, upload the logs and I’ll take a look.

**Comment by GeekyEggo** [comment] 2022-02-06 09:56
Closing this as I’ve not heard anything; if the problem persists feel free to comment.

**Closed by GeekyEggo** 2022-02-06 09:56 UTC
Labels: 🐞 bug

**Comment by MikewrightJS** [comment] 2022-02-07 13:49
I actually have the same issue with the latest version, hit the error multiple times, which log should i upload?

**Comment by GeekyEggo** [comment] 2022-02-07 14:13
Hey @MikewrightJS; if you try with [the latest beta version](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin), and if the problem persists upload the logs at `%appdata%\Elgato\StreamDeck\Plugins\com.geekyeggo.goveecontroller.sdPlugin\logs` I’ll take a look.

**Comment by MikewrightJS** [comment] 2022-02-07 15:01
[GoveeController.log](https://github.com/GeekyEggo/GoveeController/files/8016274/GoveeController.log)

**Comment by GeekyEggo** [comment] 2022-02-07 18:34
Thanks @MikewrightJS, I've updated the latest beta to help identify what's going on;

- Improve button feedback based on settings.
- Improve button feedback based on success response.
- Improve logging of global API key existence.
- Update request interception for missing API keys to not reset global settings.

Could I ask you download the [latest beta](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin), and repeat the steps above? Thanks for your help with getting to the bottom of this.

**Comment by MikewrightJS** [comment] 2022-02-07 21:40
[GoveeController.log](https://github.com/GeekyEggo/GoveeController/files/8018931/GoveeController.log)

Hello no problem. After downloading the latest beta i am getting the same issue of an empty object in data from the api.

**Comment by GeekyEggo** [comment] 2022-02-07 21:42
Hmm, so I understand correctly, is the flow:
1. Input API key successfully
2. See list of devices and setup action
3. Wait some time, see this error
4. Repeat from step 1?

**Comment by MikewrightJS** [comment] 2022-02-08 13:20
I don't make it past option 1.
![image](https://user-images.githubusercontent.com/98807207/152995284-fb755d24-4779-44d6-bd3c-ec981075b208.png)

**Comment by MikewrightJS** [comment] 2022-02-08 13:21
![image](https://user-images.githubusercontent.com/98807207/152995402-f884949c-3cec-4206-b9bb-6afe69e0fdff.png)
I dont make it past option 1 (removed api key for the screenshot)

**Comment by GeekyEggo** [comment] 2022-02-08 13:52
Good news @MikewrightJS, I think I might have found the root cause of the problem! Check out the [latest beta](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin) and let me know if it fixes it for you.
